-- Theme colors
vim.g.base_text = "#d8d8d8"
vim.g.dark_text = "#828482"
vim.g.base_bg = "#000000"
vim.g.bright_bg = "#1f1f24"

vim.g.xcode_pink = "#ff7ab2"
vim.g.xcode_pink_dark = "#98486a"
vim.g.xcode_teal = "#acf2e4"
vim.g.xcode_teal_dark = "#78c2b3"
vim.g.xcode_cyan = "#6bdfff"
vim.g.xcode_cyan_dark = "#4eb0cc"
vim.g.xcode_purple = "#dabaff"
vim.g.xcode_purple_dark = "#b281eb"
vim.g.xcode_orange = "#ffa14f"
vim.g.xcode_orange_dark = "#ff8170"
vim.g.xcode_yellow = "#d9c97c"
